# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySurvey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySurvey

  target 'MySurveyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MySurvey-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySurvey-tvOS

  target 'MySurvey-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
